#:kivy 2.3.1

<PongBall>:
    size: 40, 40
    canvas:
        Color:
            rgba: self.color
        Ellipse:
            pos: self.pos
            size: self.size

<PongPaddle>:
    size: 25, 200
    canvas:
        Color:
            rgba: self.color
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [15]

<Brickgame>:
    ball: pong_ball
    player1: player_left
    player2: player_right

    canvas:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size
            source: "background1.png"

    Label:
        font_size: 70
        center_x: root.width / 4
        top: root.top - 50
        color: 0.28, 0.24, 0.55, 1
        text: str(root.player1.score)

    Label:
        font_size: 70
        center_x: root.width * 3 / 4
        top: root.top - 50
        color: 0.28, 0.24, 0.55, 1
        text: str(root.player2.score)

    PongBall:
        id: pong_ball
        center: root.center
        color: 0, 0, 0, 1

    PongPaddle:
        id: player_left
        x: root.x
        center_y: root.center_y
        color: 1, 0, 0, 1

    PongPaddle:
        id: player_right
        x: root.width - self.width
        center_y: root.center_y
        color: 0, 0.75, 1, 1