#Kivy version unspecified!!!


<Ball>:
    size: 50, 50
    canvas: 
        Color: 
            rgba: self.color

            Ellipse:
                pos: self.pos
                size: self.size


<Paddle>:
    size: 25, 200
    canvas:
        Color:
            rgba: self.color


        RoundedRectangle:

            pos: self.pos
            size: self.size
            radius: [15]



<BrickGame>:
    ball: _ball
    player: player_



    canvas:
        Color:
            rgba: self.color

        Rectangle:
            pos: self.pos
            size: self.size
            source: "img.jpg"


    Ball:
        id: _ball
        center: self.parent.center
        color: 0, 0, 0


    Paddle:
        id: player_
        x: root.x
        center_y: root.center_y
        color: 255, 0, 0

